FROM ghcr.io/openexperiencecloud/cloud.openexperience.content.images.base:${project.version}
LABEL org.opencontainers.image.source https://github.com/OpenExperienceCloud/cloud-openexperience-content

COPY oec/seed/ /opt/oec/seed/
COPY oec/runtime/ /opt/oec/runtime/
